import type {Metadata} from "next";
import type {ReactNode} from "react";
import {notFound} from "next/navigation";
import {montserrat} from "@/app/[lang]/fonts/fonts";
import {Header} from "@/components/header/Header";
import {Footer} from "@/components/footer/Footer";
import {I18nProvider} from "@/components/i18n/I18nProvider";
import {getDictionary, hasLocale} from "@/app/[lang]/dictionaries";
import {config} from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "./globals.css";

config.autoAddCss = false;

export const generateStaticParams = async () => [{lang: "pl"}, {lang: "en"}];

export const metadata: Metadata = {
    title: "The Mars Lounge",
    description: "Generated by create next app",
};

type LangLayoutProps = {
    children: ReactNode;
    params: Promise<{ lang: string }>;
};

export default async function RootLayout({children, params}: LangLayoutProps) {
    const {lang} = await params;

    if (!hasLocale(lang)) notFound();

    const dict = await getDictionary(lang);
    return (
        <html lang={lang}>
        <body className={`${montserrat.className} antialiased`}>
        <I18nProvider dict={dict}>
            <Header/>
            {children}
            <Footer/>
        </I18nProvider>
        </body>
        </html>
    );
}
