import {montserrat} from "@/app/[lang]/fonts/fonts";
import type {Metadata} from "next";
import {Header} from "@/components/header/Header";
import "./globals.css";
import {I18nProvider} from "@/components/i18n/I18nProvider";
import {getDictionary, hasLocale} from "@/app/[lang]/dictionaries";
import {notFound} from "next/navigation";

export const generateStaticParams = async () => [{lang: 'pl'}, {lang: 'en'}];

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children, params}: LayoutProps<'/[lang]'>) {
    const { lang } = await params;
    if (!hasLocale(lang)) notFound();

    const dict = await getDictionary(lang);
    return (
        <html lang={lang}>

        <body className={`${montserrat.className} antialiased`}>
        <Header/>


        <I18nProvider dict={dict}>{children}</I18nProvider>
        </body>
        </html>
    );
}
